// Opleidingsaanbod v4 (mock-up). Prijzen en data zijn INDICATIEF en moeten door BIM4ALL bevestigd worden.
window.B4A_OPLEIDINGEN = [
  { id: 'ai-bouwpraktijk', cat: 'AI', categorie: 'AI & digitalisering', naam: 'AI in de bouwpraktijk', belofte: 'Na één dag gebruik je AI dagelijks voor offertes, planningen, verslagen en controles. Zonder gedoe, met oog voor risico\'s.', doelgroep: 'Werkvoorbereiders, projectleiders, calculatoren en modelleurs', duur: '1 dag', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Basis', prijs: 595, data: ['8 oktober 2026', '5 november 2026', '10 december 2026'], plekken: 4, populair: true },
  { id: 'ai-management', cat: 'AI', categorie: 'AI & digitalisering', naam: 'AI voor management en directie', belofte: 'Weet na een halve dag waar AI in jouw bedrijf waarde toevoegt, welke keuzes je moet maken en wat je van je mensen mag verwachten.', doelgroep: 'Directie, MT, afdelingshoofden', duur: '½ dag', vorm: 'Klassikaal', locatie: 'Rijssen of op locatie', niveau: 'Basis', prijs: 495, data: ['15 oktober 2026', '19 november 2026'], plekken: 8 },
  { id: 'copilot', cat: 'AI', categorie: 'AI & digitalisering', naam: 'Slimmer werken met Copilot', belofte: 'Haal meer uit Microsoft 365 met Copilot in Outlook, Teams, Word en Excel. Direct toepasbaar op je eigen werk.', doelgroep: 'Alle kantoormedewerkers', duur: '2 × 2 uur', vorm: 'Online', locatie: 'Online', niveau: 'Basis', prijs: 295, data: ['21 oktober 2026', '25 november 2026'], plekken: 12 },
  { id: 'ai-beleid', cat: 'AI', categorie: 'AI & digitalisering', naam: 'AI-beleid en verantwoord gebruik', belofte: 'Stel in één dag een werkbaar AI-beleid op: wat mag, wat niet, en hoe je dat uitlegt aan je mensen.', doelgroep: 'HR, kwaliteit, directie, IT', duur: '1 dag', vorm: 'Blended', locatie: 'Online + Rijssen', niveau: 'Verdieping', prijs: 695, data: ['29 oktober 2026'], plekken: 6 },
  { id: 'revit-arch', cat: 'BIM', categorie: 'BIM & software', naam: 'Revit Architecture basis', belofte: 'Modelleer na drie dagen zelfstandig een bouwkundig model in Revit, volgens de afspraken die in projecten gelden.', doelgroep: 'Tekenaars en modelleurs', duur: '3 dagen', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Basis', prijs: 1495, data: ['14 oktober 2026', '18 november 2026'], plekken: 3, populair: true },
  { id: 'revit-mep', cat: 'BIM', categorie: 'BIM & software', naam: 'Revit MEP voor installateurs', belofte: 'Werktuigbouwkundige en elektrotechnische installaties modelleren en coördineren in Revit.', doelgroep: 'Installatietechnisch tekenaars en modelleurs', duur: '3 dagen', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Basis', prijs: 1495, data: ['28 oktober 2026'], plekken: 5 },
  { id: 'solibri', cat: 'BIM', categorie: 'BIM & software', naam: 'Solibri modelcontrole', belofte: 'Controleer modellen op clashes, informatie-eisen en afspraken, en rapporteer zodat de keten ermee verder kan.', doelgroep: 'BIM-coördinatoren, werkvoorbereiders', duur: '2 dagen', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Verdieping', prijs: 1095, data: ['11 november 2026'], plekken: 6 },
  { id: 'acc', cat: 'BIM', categorie: 'BIM & software', naam: 'Autodesk Construction Cloud', belofte: 'Richt ACC in voor je project en werk samen met alle partijen in één omgeving.', doelgroep: 'Projectleiders, werkvoorbereiders, BIM-coördinatoren', duur: '1 dag', vorm: 'Online', locatie: 'Online', niveau: 'Basis', prijs: 545, data: ['22 oktober 2026', '2 december 2026'], plekken: 10 },
  { id: 'bim-coordinator', cat: 'Data', categorie: 'Data & informatie', naam: 'BIM-coördinator', belofte: 'Leer de coördinatie van BIM-projecten dragen: afspraken, modelcontrole, informatiemanagement en het gesprek met de keten.', doelgroep: 'Werkvoorbereiders en modelleurs met BIM-ervaring', duur: '5 dagen', vorm: 'Blended', locatie: 'Online + Rijssen', niveau: 'Verdieping', prijs: 2950, data: ['4 november 2026'], plekken: 5, populair: true },
  { id: 'ils', cat: 'Data', categorie: 'Data & informatie', naam: 'Informatiemanagement en ILS', belofte: 'Stel informatieleveringsspecificaties op die opdrachtgevers en ketenpartners begrijpen en naleven.', doelgroep: 'Informatiemanagers, BIM-coördinatoren, opdrachtgevers', duur: '2 dagen', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Verdieping', prijs: 1195, data: ['26 november 2026'], plekken: 8 },
  { id: 'powerbi', cat: 'Data', categorie: 'Data & informatie', naam: 'Data-analyse met Power BI', belofte: 'Van projectdata naar dashboards waar je op kunt sturen.', doelgroep: 'Werkvoorbereiders, planners, controllers', duur: '2 dagen', vorm: 'Online', locatie: 'Online', niveau: 'Basis', prijs: 895, data: ['3 december 2026'], plekken: 10 },
  { id: 'communiceren', cat: 'Mens', categorie: 'Mens & samenwerking', naam: 'Communiceren in projecten', belofte: 'Helder afstemmen met opdrachtgever, uitvoering en ketenpartners, ook als het spannend wordt.', doelgroep: 'Projectleiders, werkvoorbereiders, uitvoerders', duur: '2 dagen', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Basis', prijs: 995, data: ['20 oktober 2026', '1 december 2026'], plekken: 6 },
  { id: 'feedback', cat: 'Mens', categorie: 'Mens & samenwerking', naam: 'Feedback en eigenaarschap', belofte: 'Een team dat elkaar aanspreekt en verantwoordelijkheid neemt. Praktisch, met eigen casussen.', doelgroep: 'Teams en teamleiders', duur: '1 dag', vorm: 'Klassikaal', locatie: 'Rijssen of op locatie', niveau: 'Basis', prijs: 595, data: ['13 november 2026'], plekken: 8 },
  { id: 'keten', cat: 'Mens', categorie: 'Mens & samenwerking', naam: 'Samenwerken in de digitale keten', belofte: 'Wat vraagt digitaal samenwerken van gedrag, afspraken en vertrouwen tussen partijen?', doelgroep: 'Projectteams en ketenpartners', duur: '1 dag', vorm: 'Blended', locatie: 'Online + Rijssen', niveau: 'Verdieping', prijs: 695, data: ['9 december 2026'], plekken: 10 },
  { id: 'leidinggeven', cat: 'Leiderschap', categorie: 'Leiderschap & verandering', naam: 'Leidinggeven aan digitale verandering', belofte: 'Verandering laten landen bij mensen die het druk hebben. Adoptie, weerstand en ritme.', doelgroep: 'MT-leden, project- en teamleiders', duur: '2 dagen', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Verdieping', prijs: 1295, data: ['12 november 2026'], plekken: 7, populair: true },
  { id: 'adoptie', cat: 'Leiderschap', categorie: 'Leiderschap & verandering', naam: 'Adoptie van nieuwe werkwijzen', belofte: 'Van pilot naar dagelijkse praktijk: hoe zorg je dat nieuwe software en processen blijven hangen?', doelgroep: 'Digital leads, BIM-managers, kwaliteitsmanagers', duur: '1 dag', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Verdieping', prijs: 695, data: ['27 november 2026'], plekken: 8 },
  { id: 'coachend', cat: 'Leiderschap', categorie: 'Leiderschap & verandering', naam: 'Coachend leiderschap', belofte: 'Medewerkers laten groeien in plaats van sturen op de inhoud.', doelgroep: 'Leidinggevenden en teamleiders', duur: '3 dagen', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Verdieping', prijs: 1595, data: ['7 januari 2027'], plekken: 8 },
  { id: 'werkvoorbereider', cat: 'Functie', categorie: 'Functiegericht', naam: 'Werkvoorbereider 2.0', belofte: 'Werkvoorbereiding met BIM, data en AI. Een leerpad voor de werkvoorbereider van nu.', doelgroep: 'Werkvoorbereiders met enkele jaren ervaring', duur: '6 dagen', vorm: 'Blended', locatie: 'Online + Rijssen', niveau: 'Verdieping', prijs: 3450, data: ['6 november 2026'], plekken: 6 },
  { id: 'modelleur', cat: 'Functie', categorie: 'Functiegericht', naam: 'BIM-modelleur', belofte: 'Van tekenaar naar modelleur: Revit, afspraken en informatie in één traject.', doelgroep: 'Tekenaars', duur: '8 dagen', vorm: 'Blended', locatie: 'Online + Rijssen', niveau: 'Basis', prijs: 3950, data: ['20 november 2026'], plekken: 6 },
  { id: 'projectleider', cat: 'Functie', categorie: 'Functiegericht', naam: 'Projectleider in een digitale organisatie', belofte: 'Sturen op informatie, mensen en samenwerking in projecten die steeds digitaler worden.', doelgroep: 'Projectleiders', duur: '4 dagen', vorm: 'Klassikaal', locatie: 'Utrecht', niveau: 'Verdieping', prijs: 2450, data: ['14 januari 2027'], plekken: 8 },
];
// Verrijking (B1, B3, B6): afgeleid uit duur; INDICATIEF.
(function () {
  const maanden = ['januari','februari','maart','april','mei','juni','juli','augustus','september','oktober','november','december'];
  const parse = (t) => { const [d, m, y] = t.split(' '); return new Date(+y, maanden.indexOf(m), +d); };
  const fmt = (d) => d.getDate() + ' ' + maanden[d.getMonth()] + ' ' + d.getFullYear();
  const dagen = (o) => { const m = o.duur.match(/(\d+)/); if (o.duur.includes('½') || o.duur.includes('×')) return 1; return m ? +m[1] : 1; };
  const alg = {
    resultaten: (o) => [({ AI: 'Je weet welke AI-tools nu al betrouwbaar werken in jouw functie, en welke niet', BIM: 'Je werkt zelfstandig volgens de afspraken die in projecten gelden', Data: 'Je vertaalt informatie-eisen naar controleerbare afspraken', Mens: 'Je voert het gesprek dat je nu uit de weg gaat', Leiderschap: 'Je laat verandering landen bij mensen die het druk hebben', Functie: 'Je beheerst de digitale kant van je functie van basis tot verdieping' })[o.cat], 'Direct toepasbaar op je eigen projecten en documenten', 'Afspraken die je meeneemt naar je team'],
    programma: (o, n) => {
      if (o.cat === 'AI' && n === 1) return [{ dag: 'Dag 1', start: '09.00', eind: '16.30', punten: ['Waar staat AI vandaag: wat werkt in de bouw, wat is hype', 'Aan het werk met je eigen offertes, planningen, verslagen en bestekken', 'AI naast BIM: modelinformatie bevragen, controles versnellen', 'Privacy, aansprakelijkheid en afspraken binnen je team', 'Je eigen werkwijze voor morgen'] }];
      const p = []; const thema = ['Basis en context: waarom, voor wie, welke afspraken gelden', 'Verdieping: de onderdelen die in de praktijk het meeste tijd kosten', 'Toepassen: eigen casussen en project', 'Coördinatie en samenwerking in de keten', 'Kwaliteit, controle en overdracht', 'Eigen plan: wat doe je anders vanaf volgende week', 'Verdieping op jullie software en afspraken', 'Presentatie en afronding'];
      for (let i = 0; i < Math.min(n, 8); i++) p.push({ dag: 'Dag ' + (i + 1), start: '09.00', eind: '16.30', punten: [thema[i] || thema[thema.length - 1], 'Oefenen met een realistisch project', 'Reflectie en vragen uit de praktijk'], tussen: i < n - 1 ? 'Praktijkopdracht in je eigen werk (ca. 2 uur)' : null });
      return p;
    },
  };
  for (const o of window.B4A_OPLEIDINGEN) {
    const n = dagen(o);
    o.aantalDagen = n;
    o.doorlooptijd = n <= 1 ? '1 dag' : (n <= 3 ? n + ' dagen in ' + (n) + ' weken' : n + ' dagen in ' + Math.round(n * 1.5) + ' weken');
    o.zelfstudie = o.vorm === 'Blended' ? (n * 3) + ' uur online, in eigen tijd' : (n <= 1 ? 'Geen' : 'Ca. ' + (n * 2) + ' uur praktijkopdrachten');
    o.groep = 'Max. 10 deelnemers';
    o.certificaat = o.cat === 'BIM' || o.cat === 'Data' || o.cat === 'Functie' ? 'Certificaat BIM4ALL Academie' : 'Deelnamecertificaat';
    o.inbegrepen = ['Lesmateriaal en oefenbestanden', 'Een jaar toegang tot de online leeromgeving', o.vorm === 'Online' ? 'Opnames van de sessies' : 'Lunch en koffie in Rijssen'];
    if (o.id === 'bim-coordinator') { o.inbegrepen.push('Eerste jaar lidmaatschap BIM4ALL Kring'); }
    o.resultaten = alg.resultaten(o);
    o.programma = alg.programma(o, n);
    o.starts = o.data.map((d0) => { const d = parse(d0); const ds = []; for (let i = 0; i < n; i++) { const x = new Date(d); x.setDate(d.getDate() + i * 7); ds.push(fmt(x)); } return { start: d0, dagen: ds, plekken: o.plekken }; });
    o.score = (8.8 + ((o.id.length * 7) % 5) / 10).toFixed(1).replace('.', ',');
    o.reviews = 12 + (o.id.length * 3) % 20;
  }
})();

window.B4A_ARTIKELEN = [
  { id: 'ai-wat-werkt-vandaag', thema: 'AI & productiviteit', titel: 'Praktische AI in de bouw: wat werkt vandaag al, en wat nog niet', intro: 'Geen visie op 2030, maar wat je deze maand kunt inzetten in werkvoorbereiding, calculatie en projectleiding. En waar je nog van af moet blijven.', datum: '2 september 2026', auteur: 'Herwin Voortman', leestijd: '6 min', opleiding: 'ai-bouwpraktijk', oplossing: { naam: 'Strategy: AI-beleid en roadmap', href: '../v3/Strategy.dc.html' }, foto: 'assets/opt/brummelhuis-revit.jpg' },
  { id: 'human-in-the-loop', thema: 'Mens & verandering', titel: 'Human in the loop: waarom adoptie belangrijker is dan technologie', intro: 'De meeste digitaliseringstrajecten mislukken niet op software. Ze mislukken op mensen die er niet mee gaan werken. Vijf lessen uit onze projecten.', datum: '19 augustus 2026', auteur: 'Melvin van Puffelen', leestijd: '5 min', opleiding: 'adoptie', oplossing: { naam: 'Transformation: implementatie en adoptie', href: '../v3/Transformation.dc.html' }, foto: 'assets/hollander-gesprek.jpeg' },
  { id: 'van-skills-gap-naar-leercultuur', thema: 'Leren & organisatie', titel: 'Van skills gap naar leercultuur: zo bouw je een lerende organisatie', intro: 'Een training lost een tekort op. Een leercultuur voorkomt het volgende. Wat HR en directie daarvoor moeten regelen, en wat juist niet.', datum: '5 augustus 2026', auteur: 'Melvin van Puffelen', leestijd: '7 min', opleiding: 'leidinggeven', oplossing: { naam: 'Incompany en leerpaden', href: 'Incompany v4.dc.html' }, foto: 'assets/opt/foto-leertrajecten.jpg' },
  { id: 'functies-veranderen', thema: 'Toekomst van werk', titel: 'Welke functies in de bouw veranderen door AI, en wat dat vraagt van HR', intro: 'Werkvoorbereider, calculator, tekenaar: het werk verschuift van maken naar controleren en afstemmen. Hoe je daar nu al op voorsorteert.', datum: '15 juli 2026', auteur: 'Melvin van Puffelen', leestijd: '8 min', opleiding: 'werkvoorbereider', oplossing: { naam: 'Digital Fit Partnership', href: '../v3/Voor organisaties.dc.html' }, foto: 'assets/vastbouw-overleg.jpeg' },
  { id: 'ils-in-de-praktijk', thema: 'BIM & informatie', titel: 'Een ILS die de keten ook echt gebruikt', intro: 'Informatieleveringsspecificaties stranden vaak op papier. Drie dingen die opdrachtgevers anders doen als het wel werkt.', datum: '24 juni 2026', auteur: 'Herwin Voortman', leestijd: '5 min', opleiding: 'ils', oplossing: { naam: 'Transformation: processen en standaarden', href: '../v3/Transformation.dc.html' }, foto: 'assets/roc-overleg.jpeg' },
  { id: 'samenwerken-digitale-keten', thema: 'Mens & verandering', titel: 'Digitaal samenwerken is vooral samenwerken', intro: 'Modellen delen is techniek. Elkaar vertrouwen op wat erin staat is gedrag. Waarom soft skills de harde kant van BIM zijn.', datum: '3 juni 2026', auteur: 'Herwin Voortman', leestijd: '4 min', opleiding: 'keten', oplossing: { naam: 'Capability: mens en samenwerking', href: '../v3/Capability.dc.html' }, foto: 'assets/foto-training-overleg.jpeg' },
];

window.B4A_EVENTS = [
  { id: 'kennisontbijt-ai', soort: 'Kennisontbijt', toegang: 'Open inschrijving', titel: 'AI in de bouw: wat werkt vandaag', datum: '1 oktober 2026', tijd: '08.00 tot 10.00 uur', locatie: 'Rijssen', vorm: 'Fysiek · Rijssen', voor: 'Directie, MT en HR', prijs: 'Prijs: te bepalen door BIM4ALL', tekst: 'Anderhalf uur praktijkvoorbeelden uit werkvoorbereiding en calculatie, daarna vragen. Geen verkooppraatje, wel een eerlijk beeld van wat AI nu kan.', plekken: 3 },
  { id: 'bim-cafe', soort: 'BIM-café', toegang: 'Open inschrijving', titel: 'Modelcontrole in de keten', datum: '22 oktober 2026', tijd: '16.00 tot 18.30 uur', locatie: 'Rijssen', vorm: 'Fysiek · Rijssen', voor: 'BIM-coördinatoren en modelleurs', prijs: 'Prijs: te bepalen door BIM4ALL', tekst: 'Informele middag met een casus uit de praktijk, een korte demo en tijd om collega\'s van andere bedrijven te spreken.', plekken: 5 },
  { id: 'webinar-functies', soort: 'Webinar', toegang: 'Open inschrijving', titel: 'Hoe verandert AI het werk van je mensen?', datum: '12 november 2026', tijd: '12.00 tot 13.00 uur', locatie: 'Online', vorm: 'Online', voor: 'HR en L&D', prijs: 'Prijs: te bepalen door BIM4ALL', tekst: 'Welke functies veranderen, welke vaardigheden ontstaan en hoe je daar een ontwikkelplan van maakt. Met ruimte voor jouw vragen.', plekken: 40 },
  { id: 'alumni-sessie', soort: 'Alumni-sessie', toegang: 'Open inschrijving', titel: 'Terugkomdag BIM-coördinatoren', datum: '10 december 2026', tijd: '13.00 tot 17.00 uur', locatie: 'Rijssen', vorm: 'Fysiek · Rijssen', voor: 'Oud-deelnemers BIM-coördinator', prijs: 'Inbegrepen voor oud-deelnemers', tekst: 'Wat is er sinds de opleiding veranderd in je werk? Nieuwe ontwikkelingen in software en afspraken, en elkaars casussen.', plekken: 12 },
  { id: 'directietafel', soort: 'Besloten sessie · Directietafel', toegang: 'Open inschrijving', titel: 'Wat doet AI met ons bedrijfsmodel?', datum: '5 november 2026', tijd: '15.00 tot 18.00 uur', locatie: 'Rijssen', vorm: 'Fysiek · Rijssen', voor: 'Directie en MT', prijs: 'Voor partners', tekst: 'Twaalf directieleden, één vraag: waar verdienen we over vijf jaar ons geld mee, en wat vraagt dat nu van onze mensen? Wat besproken wordt, blijft aan tafel.', plekken: 2 },
  { id: 'hr-tafel', soort: 'Besloten sessie · HR-tafel', toegang: 'Open inschrijving', titel: 'Functies die veranderen, skills die ontbreken', datum: '26 november 2026', tijd: '13.00 tot 16.00 uur', locatie: 'Rijssen', vorm: 'Fysiek · Rijssen', voor: 'HR en L&D', prijs: 'Voor partners', tekst: 'Hoe brengen leden skills in beeld en wat doen ze met de uitkomst? Twee leden delen hun aanpak, daarna werken we aan die van jou.', plekken: 4 },
  { id: 'bim-tafel', soort: 'Besloten sessie · BIM-tafel', toegang: 'Open inschrijving', titel: 'Afspraken die de keten wél naleeft', datum: '14 januari 2027', tijd: '13.00 tot 16.00 uur', locatie: 'Rijssen', vorm: 'Fysiek · Rijssen', voor: 'BIM-coördinatoren en digital leads', prijs: 'Voor partners', tekst: 'ILS, modelcontrole en het gesprek met onderaannemers. Casus van een lid, daarna elkaars protocollen naast elkaar.', plekken: 9 },
];
